# -*- coding: utf-8 -*-
"""Sales forcasting .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17w0t43Y7XIeoKVwzhh0Wlm6qgrZHliGA
"""

import pandas as pd

from google.colab import files
uploaded= files.upload()

df= pd.read_csv("train.csv")
df

# Step 3: Show basic information
print("Dataset shape:", df.shape)
print("\nFirst five rows:")
display(df.head())

# Step 4: Overview of column data types and missing values
print("\nDataset Info:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

"""Data Cleaning & Preprocessing
Goals:

Convert date columns to datetime format

Drop unnecessary columns (like Row ID)

Decide how to handle the missing postal codes

Ensure numerical data is correctly typed

(Optional) Create a new column for aggregated daily sales for forecasting.
"""

# Convert Order Date and Ship Date to datetime with dayfirst=True
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)

# Drop 'Row ID' – not meaningful
df.drop(columns=['Row ID'], inplace=True)

# Check missing Postal Code entries
print("Missing postal codes:")
print(df[df['Postal Code'].isnull()][['City', 'State']].drop_duplicates())

# Desired ZIP code to use for Burlington, Vermont
default_burlington_zip = 5401  # We search the internet for the Postal Code

# Impute missing postal codes specifically for Burlington, VT
mask = df['Postal Code'].isnull() & \
       (df['City'] == 'Burlington') & \
       (df['State'] == 'Vermont')
df.loc[mask, 'Postal Code'] = default_burlington_zip

# Recheck missing values across dataset
print("\nRemaining missing values after ZIP imputation:")
print(df.isnull().sum())

"""EDA Step 1: Sales Trends Over Time
Objective:

Aggregate daily sales

Visualize overall trend

Optionally smooth using rolling average
"""

#Time-Series Analysis
import matplotlib.pyplot as plt
import seaborn as sns
# Set plot style
sns.set(style="whitegrid")
plt.figure(figsize=(14, 6))

# Group by order date and sum sales
daily_sales = df.groupby('Order Date')['Sales'].sum().reset_index()

# Sort by date to ensure correct plotting
daily_sales.sort_values('Order Date', inplace=True)

# Plot daily sales
plt.plot(daily_sales['Order Date'], daily_sales['Sales'], label='Daily Sales', alpha=0.6)

# Add rolling average (7-day)
daily_sales['Rolling Avg'] = daily_sales['Sales'].rolling(window=7).mean()
plt.plot(daily_sales['Order Date'], daily_sales['Rolling Avg'], color='red', label='7-Day Rolling Average')

# Plot daily sales
plt.plot(daily_sales['Order Date'], daily_sales['Sales'], label='Daily Sales', alpha=0.6)

# Add rolling average (7-day)
daily_sales['Rolling Avg'] = daily_sales['Sales'].rolling(window=7).mean()
plt.plot(daily_sales['Order Date'], daily_sales['Rolling Avg'], color='red', label='7-Day Rolling Average')

# Titles and labels
plt.title("Daily Sales Over Time", fontsize=16)
plt.xlabel("Date")
plt.ylabel("Sales")
plt.legend()
plt.tight_layout()
plt.show()

"""Analysis of Daily Sales Trend
📈 Overall Trend
The rolling average (red line) shows a mild upward trend over the 4-year span.

There’s increased sales activity in the second half of the dataset (2017–2018) compared to the earlier years (2015–2016).

🔁 Seasonality
There are recurring patterns of sales spikes:

Typically around end-of-year (Q4) → likely holiday season sales (e.g. November–December).

Some spikes mid-year (June–July) could indicate mid-year promotions.

🚀 Sales Spikes & Outliers
Several sharp, high-volume spikes (especially early 2015, late 2016, and 2018).

These spikes could be:

Bulk purchases
B2B transactions
Special campaigns or promotions
One extreme spike in early 2015 surpasses $25,000 in a single day — worth isolating later to investigate the product or customer behind it.

🛑 Volatility
The blue line (raw daily sales) shows high volatility.

Daily sales are often very low (near zero), with intermittent high-value days — suggesting lumpy demand, not steady daily flow.

This may affect how we approach forecasting — we'll likely need smoothing, aggregation, or specialized models like Prophet or XGBoost with calendar features.

EDA Step 2: Breakdown by Year
Objective:

Visualize total yearly sales

Compare year-over-year growth
"""

# Extract year from Order Date
df['Year'] = df['Order Date'].dt.year

# Aggregate sales by year
yearly_sales = df.groupby('Year')['Sales'].sum().reset_index()

# Plot
plt.figure(figsize=(10, 5))
sns.barplot(data=yearly_sales, x='Year', y='Sales', hue='Year', palette='viridis', legend=False)

# Labels and titles
plt.title("Total Sales by Year", fontsize=16)
plt.xlabel("Year")
plt.ylabel("Total Sales")
plt.tight_layout()
plt.show()

"""Yearly Sales Trend Analysis
Sales increased significantly over time, especially after 2016.

Growth pattern:

2015 → 2016: Slight drop (~2–4%)

2016 → 2017: Noticeable increase (≈ +30%)

2017 → 2018: Continued strong growth (≈ +20%)

This shows accelerating business performance, likely due to:

Expanded customer base

Better marketing or promotions

High-performing product categories or regions

EDA Step 3: Regional Sales Analysis
Objectives:

Compare total sales by region

Identify top-performing and underperforming regions

Visualize patterns clearly using bar plots
"""

# Group sales by Region
region_sales = df.groupby('Region')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False)

# Plot
plt.figure(figsize=(10, 5))
sns.barplot(data=region_sales, x='Region', y='Sales', palette='magma')

# Labels and title
plt.title("Total Sales by Region", fontsize=16)
plt.xlabel("Region")
plt.ylabel("Total Sales")
plt.tight_layout()
plt.show()

"""Regional Sales Analysis
West region leads with the highest total sales, just above $700,000.

East follows closely — strong performance, nearly matching the West.

Central and South lag significantly, with the South generating the lowest sales (~$390,000).

Insight: West and East are the core revenue drivers, suggesting higher market maturity or stronger customer bases. Central and South could represent growth opportunities with targeted marketing or logistics improvements.

EDA Step 4: Category & Sub-Category Sales Analysis
Objectives:

Identify which categories drive the most revenue

Break down performance by sub-category

Spot niches with low sales (potential for improvement or removal)
"""

# Total Sales by Category
category_sales = df.groupby('Category')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False)

# Plot
plt.figure(figsize=(8, 5))
sns.barplot(data=category_sales, x='Category', y='Sales', palette='Set2')
plt.title("Total Sales by Category", fontsize=16)
plt.xlabel("Category")
plt.ylabel("Sales")
plt.tight_layout()
plt.show()

"""Category-Level Sales Analysis
Technology is the top-selling category, generating the highest revenue (~$830,000).

Furniture and Office Supplies are close behind, but clearly lag Technology.

All three categories contribute significantly, suggesting a diverse product mix.

Insight: Technology is likely the most profitable or in-demand segment. However, the gap isn’t huge — all categories are worth maintaining or expanding strategically.

EDA Step 5: Total Sales by Sub-Category
"""

# Total Sales by Sub-Category
subcat_sales = df.groupby('Sub-Category')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False)

# Plot
plt.figure(figsize=(14, 6))
sns.barplot(data=subcat_sales, x='Sub-Category', y='Sales', palette='cubehelix')
plt.title("Total Sales by Sub-Category", fontsize=16)
plt.xlabel("Sub-Category")
plt.ylabel("Sales")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Sub-Category Sales Analysis
Top Performers:

📱 Phones and 💺 Chairs dominate, each generating over $300,000 in sales.

Followed by Storage, Tables, and Binders — strong secondary contributors.

Mid-Tier:

Items like Machines, Accessories, and Copiers also contribute meaningfully.

Low Performers:

🖼️ Art, ✉️ Envelopes, 🏷️ Labels, and 📎 Fasteners have very low sales, likely niche or low-demand products.

📌 Insight: Focus on expanding inventory and promotions around high-performing sub-categories. Consider evaluating pricing, marketing, or even phasing out low-sales items if margins are poor.

EDA Step 5: Customer Segment Analysis
Objectives:

Identify which customer segments drive the most revenue

Compare performance between segments

Guide targeting strategies (B2B vs B2C)
"""

# Total Sales by Customer Segment
segment_sales = df.groupby('Segment')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False)

# Plot
plt.figure(figsize=(8, 5))
sns.barplot(data=segment_sales, x='Segment', y='Sales', palette='pastel')

# Labels and title
plt.title("Total Sales by Customer Segment", fontsize=16)
plt.xlabel("Segment")
plt.ylabel("Sales")
plt.tight_layout()
plt.show()

"""Customer Segment Analysis
Consumers are the dominant revenue source, contributing over $1.1 million — nearly half of total sales.

Corporate customers follow with strong performance (~$670K).

Home Office accounts for the smallest share, around $430K.

📌 Insight: Consumer segment is clearly the core market, but Corporate still offers significant value. Home Office may benefit from targeted offers or better product-market fit strategies to increase engagement.

Forecasting Sales for the Next 7 Days Using Prophet Model
Objective:

Build a model to predict daily sales for the 7 days following the last date in the dataset.

Prepare Data for Forecasting
We’ll start with a simple, interpretable baseline using:

Daily aggregated sales

A forecast method like Prophet (good for business data with seasonality)
"""

# Import Prophet
from prophet import Prophet

# Step 1: Aggregate daily sales
ts_df = df.groupby('Order Date')['Sales'].sum().reset_index()

# Step 2: Rename columns to match Prophet's expected input
ts_df.columns = ['ds', 'y']  # ds = date, y = value to forecast

# Step 3: Initialize and fit the Prophet model
model = Prophet(daily_seasonality=True)
model.fit(ts_df)

# Step 4: Create future dataframe for next 7 days
future = model.make_future_dataframe(periods=7)
forecast = model.predict(future)

# Step 5: Plot forecast
model.plot(forecast)
plt.title("7-Day Sales Forecast")
plt.xlabel("Date")
plt.ylabel("Predicted Sales")
plt.tight_layout()
plt.show()

# Get last date in original dataset
last_date = ts_df['ds'].max()

# Filter only the next 7 days
future_forecast = forecast[forecast['ds'] > last_date][['ds', 'yhat', 'yhat_lower', 'yhat_upper']].copy()

# Rename columns for clarity
future_forecast.rename(columns={
    'ds': 'Date',
    'yhat': 'Predicted Sales',
    'yhat_lower': 'Lower Bound',
    'yhat_upper': 'Upper Bound'
}, inplace=True)

# Calculate average predicted sales
avg_sales = future_forecast['Predicted Sales'].mean()

# Create a new row for the average
average_row = pd.DataFrame({
    'Date': ['Average'],
    'Predicted Sales': [round(avg_sales, 2)],
    'Lower Bound': [None],
    'Upper Bound': [None]
})

# Append the row to the forecast DataFrame
forecast_with_avg = pd.concat([future_forecast, average_row], ignore_index=True)

# Display
print("📅 7-Day Sales Forecast with Average:")
display(forecast_with_avg)

"""Prophet Model Forecast
The Prophet model predicts an average of ~2,002 units/day over the next 7 days. The forecast indicates stable sales without extreme volatility, guiding moderate restocking and staffing needs.

Forecasting Sales for the Next 7 Days Using Seasonal Autoregressive Integrated Moving Average (SARIMA)
"""

!pip install statsmodels
!pip install pmdarima

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAX

# Prepare the daily sales time series
ts_df = df.groupby('Order Date')['Sales'].sum().reset_index()
ts_df.set_index('Order Date', inplace=True)

# Ensure index is datetime
ts_df.index = pd.to_datetime(ts_df.index)

# Optional: Plot to visualize
ts_df['Sales'].plot(figsize=(14, 5), title="Daily Sales Time Series")
plt.ylabel("Sales")
plt.show()

"""Automatically Select SARIMA Parameters
Why use auto_arima?

It performs a stepwise search over ARIMA/SARIMA order combinations

Selects optimal parameters based on AIC, BIC, etc.

Handles differencing terms and seasonality intelligently
"""

import pmdarima as pm

# Prepare your series (ts_df from earlier, indexed by date, daily frequency)
y = ts_df['Sales']

# Run auto_arima with daily seasonality (m=7)
auto_model = pm.auto_arima(
    y,
    seasonal=True,
    m=7,              # weekly seasonality
    stepwise=True,
    trace=True,
    error_action='ignore',
    suppress_warnings=True
)

# View best model details
print("✅ Best SARIMA model:", auto_model.summary())

#Fit SARIMA & Forecast Next 7 Days
from statsmodels.tsa.statespace.sarimax import SARIMAX

# Fit SARIMA model
model = SARIMAX(
    ts_df['Sales'],
    order=(0, 1, 1),
    seasonal_order=(1, 0, 0, 7),
    enforce_stationarity=False,
    enforce_invertibility=False
)
sarima_result = model.fit(disp=False)

# Forecast next 7 days
forecast_steps = 7
sarima_forecast = sarima_result.get_forecast(steps=forecast_steps)

# Extract forecast and confidence intervals
forecast_mean = sarima_forecast.predicted_mean
conf_int = sarima_forecast.conf_int()

# Build forecast DataFrame
sarima_output = pd.DataFrame({
    'Date': pd.date_range(start=ts_df.index[-1] + pd.Timedelta(days=1), periods=forecast_steps),
    'Predicted Sales': forecast_mean.values,
    'Lower Bound': conf_int.iloc[:, 0].clip(lower=0).values,
    'Upper Bound': conf_int.iloc[:, 1].values
})

# Add average row
avg_row = pd.DataFrame({
    'Date': ['Average'],
    'Predicted Sales': [round(sarima_output['Predicted Sales'].mean(), 2)],
    'Lower Bound': [None],
    'Upper Bound': [None]
})

sarima_output = pd.concat([sarima_output, avg_row], ignore_index=True)

# Display the forecast
print("📊 7-Day Sales Forecast (SARIMA):")
display(sarima_output)

"""Interpretation
The SARIMA model predicts higher average sales than Prophet (~2,908 vs ~2,003).

It suggests a consistent daily demand between 2,800–3,100 units.

The confidence intervals are wider (upper bound up to ~7,900), which still reflects the historical volatility of the dataset.
"""

#SARIMA vs Prophet
# Prepare Prophet data (excluding average row)
prophet_clean = forecast_with_avg[forecast_with_avg['Date'] != 'Average'].copy()
prophet_clean['Date'] = pd.to_datetime(prophet_clean['Date'])

# Prepare SARIMA data (excluding average row)
sarima_clean = sarima_output[sarima_output['Date'] != 'Average'].copy()
sarima_clean['Date'] = pd.to_datetime(sarima_clean['Date'])

# Merge both forecasts on Date
comparison = pd.merge(
    sarima_clean[['Date', 'Predicted Sales']],
    prophet_clean[['Date', 'Predicted Sales']],
    on='Date',
    suffixes=('_SARIMA', '_Prophet')
)

# Optional: Add difference column
comparison['Difference'] = comparison['Predicted Sales_SARIMA'] - comparison['Predicted Sales_Prophet']

# Display
print("📊 SARIMA vs Prophet – 7-Day Forecast Comparison:")
display(comparison)

"""📊 Forecasting Conclusion: SARIMA vs Prophet
We compared two time-series models to forecast 7 days of retail sales:

Model	Avg. Predicted Sales	Forecast Nature	Strengths
SARIMA	~2,908 units/day	Higher, seasonality-aware	Captures recent trends & seasonality
Prophet	~2,003 units/day	Conservative, smoother	Easy to interpret, stable forecasts
🔍 Observations:
SARIMA consistently predicts higher sales, with differences of +380 to +1,492 units/day compared to Prophet.
Prophet is more cautious and may underpredict during high-variance or post-holiday periods.
Both models show strong seasonality, but SARIMA adapts better to recent high demand.
✅ Recommendation:
Use SARIMA when planning for growth or peak season logistics.
Use Prophet for baseline operations or risk-averse inventory decisions.
For balanced planning, consider averaging both models' predictions.
✅ Summary
Through a blend of exploratory data analysis and time-series modeling, we identified key revenue drivers across geography, categories, and segments. We also produced 7-day forecasts using Prophet and SARIMA, where SARIMA showed stronger sensitivity to seasonality and recent spikes.

This notebook demonstrates a complete retail analytics pipeline — from data cleaning to business-ready forecasting.
"""